change messages
AlexaEgorova/MisisVoiceAssistant pull request #1
Opened 2022-11-03 02:26 UTC by Yana999

Исправила тексты сообщений

2022-11-03 02:57 UTC, Yana999 commented
Пока не проверяла, хз как

2022-11-04 18:50 UTC, maxim1317 requested changes

2022-11-04 18:50 UTC, maxim1317 commented on src/bot.py
> +        query.answer("Спасибо за оценку! Сообщение отвправлено модераторам, новый ответ на ваш вопрос будет отправлен через некоторое время")
Вот эту часть не понял
Если что, это сообщение, которое вылезает сверху, когда жмякаешь на кнопку голосование
Можно, например, если оценка 0, написать, что ссорямба, мы все проверим и поправим в следующей версии", а если все хорошо, то пусть идет дальше

2022-11-04 18:50 UTC, maxim1317 commented on src/bot.py
> +            'Задать вопрос о МИСиС',
Ненене, это мы регаем команду бота. 
Команды бота это `/[a-z_]+` насколько я знаю
Описание можно поменять в @BotFather

2022-11-04 18:50 UTC, maxim1317 commented on src/bot.py
> -        return (
Я бы оставил такой формат для админов, а для пользователей да, стоит убрать изнанку

2022-11-04 18:50 UTC, maxim1317 commented on src/bot.py
> +                "\n-Отвечать на текстовые вопросы сообщением"
Упадет, стоит прогнать через prepare_text (символы `-` и `.` должны экранироваться)

2022-11-04 18:50 UTC, maxim1317 commented on src/bot.py
> +        return prepare_text(self.answer)
Стоит prepare_text перенести наверз тогда, а то я не уверен, что он объявлен в этот момент

2022-11-05 20:41 UTC, AlexaEgorova approved these changes

2022-11-05 20:41 UTC, merged